### ISSUE TITLE
Update shows menu even without child permission

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/menus#17]
This is  a **bug**.

### Prerequisites
yes

### Description

Menu checking somehow shows menu entries that the user doesn't have permission for now

### Steps to Reproduce
1. Have a menu structure with a child that a role doesn't have access to (f.e. `foo.bar.index`), being a child of a `has_children` `foo` menu
2. Log in as that user, the `api/core/home` request still returns this menu, even if the user doesn't have the permissions for that route

### Expected behavior

TreeBuilder to only return menu items that the user(role) has access to 

### Actual behavior

Seemingly returning all menu items (from a brief glance system & admin is also returned)

Note: I have an overridden `AppState` (residing under `App\Http\Responses`) however I took over the updated AppState from the 3.3 upgrade and haven't changed any BE code related to the menutree; so that should be unrelated

**Comment by aocneanu** [comment]
Trying to reproduce I removed the `system.tutorials.index` permission from the `admin` role and reloaded the window and everything looks ok.

![image](https://user-images.githubusercontent.com/16073274/58366527-49f1d080-7edc-11e9-9e4a-d91afd7b5984.png)

**Comment by jlsjonas** [comment]
Admin wouldn't cause it indeed...
I just found the culprit

in `TreeBuilder.php`'s `permissions()` you check the permissions of the first user, instead of the current user
![image](https://user-images.githubusercontent.com/932193/58413370-e0f38f80-8078-11e9-82bc-eba3b6217e8a.png)

so the permissions (menu structure) would only be correct for users with the same role as the _first_ user in the DB

**Comment by aocneanu** [comment]
Oh wow....
